import colors from "./export.scss";

export default {
  color_primary: colors["color-primary"],
  color_secondary: colors["color-secondary"],
  color_tertiary: colors["color-tertiary"],
  color_text_primary: colors["color-text-primary"],
  color_text_secondary: colors["color-text-secondary"],
  color_text_tertiary: colors["color-text-tertiary"],
  color_text_success: colors["color-text-success"],
  color_text_warning: colors["color-text-warning"],
  color_text_error: colors["color-text-error"],
  color_text_invert_primary: colors["color-text-invert-primary"],
  color_text_invert_secondary: colors["color-text-invert-secondary"],
  color_text_invert_tertiary: colors["color-text-invert-tertiary"],
  color_icon_primary: colors["color-icon-primary"],
  color_icon_secondary: colors["color-icon-secondary"],
  color_icon_tertiary: colors["color-icon-tertiary"],
  color_icon_success: colors["color-icon-success"],
  color_icon_error: colors["color-icon-error"],
  color_icon_invert_primary: colors["color-icon-invert-primary"],
  color_icon_invert_secondary: colors["color-icon-invert-secondary"],
  color_icon_invert_tertiary: colors["color-icon-invert-tertiary"],
  color_button_primary_default: colors["color-button-primary-default"],
  color_button_primary_hover: colors["color-button-primary-hover"],
  color_button_primary_focus: colors["color-button-primary-focus"],
  color_button_primary_disable: colors["color-button-primary-disable"],
  color_button_secondary_default: colors["color-button-secondary-default"],
  color_button_secondary_hover: colors["color-button-secondary-hover"],
  color_button_secondary_focus: colors["color-button-secondary-focus"],
  color_button_secondary_disable: colors["color-button-secondary-disable"],
  color_button_invert_default: colors["color-button-invert-default"],
  color_button_invert_hover: colors["color-button-invert-hover"],
  color_button_invert_focus: colors["color-button-invert-focus"],
  color_button_invert_disable: colors["color-button-invert-disable"],
  color_background_primary: colors["color-background-primary"],
  color_background_secondary: colors["color-background-secondary"],
  color_border_primary: colors["color-border-primary"],
  color_border_secondary: colors["color-border-secondary"],
  color_border_success: colors["color-border-success"],
  color_border_warning: colors["color-border-warning"],
  color_border_error: colors["color-border-error"],
  color_control_active: colors["color-control-active"],
  color_control_active_disable: colors["color-control-active-disable"],
  color_control_default: colors["color-control-default"],
  color_control_default_disable: colors["color-control-default-disable"],
};
